<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Nutzungsbedingungen</title>
</head>
<body class="bg">
<jsp:include page="/include/header.jsp"></jsp:include>
<div class="content">
<div class="formular-bd opindex w-75 m-auto">
<p><strong>Allgemeine Datenschutz- und Nutzungsbestimmungen</strong></p>
<p><br /><strong>§ 1 Information über die Erhebung personenbezogener Daten und Anbieterkennzeichnung</strong></p>
<p>1. Im Folgenden informieren wir über die Erhebung personenbezogener Daten bei Nutzung dieser Webseite. Personenbezogene Daten sind alle Daten, die auf Sie persönlich beziehbar sind, also zum Beispiel Name, Adresse, E-Mail-Adresse, Nutzungsverhalten.<br /><br />2. Dienstanbieter gemäß § 13 Telemediengesetz (TMG) und verantwortliche Stelle gemäß § 3 Abs. 7 Bundesdatenschutzgesetz (BDSG) ist der „Arbeitskreis Alkohol und Verantwortung" des BSI (Bundesverband der Deutschen Spirituosen-Industrie und -Importeure e. V.) Geschäftsführung: Dipl.-Volksw. Angelika Wiesgen-Pick.</p>
<p><strong>§ 2 Erhebung personenbezogener Daten bei informatorischer Nutzung</strong></p>
<p class="p1"><span class="s1">1. Bei der bloß informatorischen Nutzung der Webseite, also wenn Sie sich nicht zur Nutzung der Webseite anmelden, registrieren oder uns sonst Informationen übermitteln, erheben wir keine personenbezogenen Daten, mit Ausnahme der Daten, die Ihr Browser übermittelt, um Ihnen den Besuch der Webseite zu ermöglichen. Diese sind: </span></p>
<p class="p1"><span class="s1">- IP-Adresse <br />- Datum und Uhrzeit der Anfrage <br />- Zeitzonendifferenz zur Greenwich Mean Time (GMT) <br />- Inhalt der Anforderung (konkrete Seite) <br />- Zugriffsstatus/HTTP-Statuscode <br />- jeweils übertragene Datenmenge <br />- Website, von der die Anforderung kommt <br />- Browser <br />- Betriebssystem und dessen Oberfläche <br />- Sprache und Version der Browsersoftware. </span></p>
<p class="p1"><span class="s1">2. Weiterhin werden bei Nutzung der Webseite Cookies auf Ihrem Rechner gespeichert. Ein Cookie ist eine kleine Textdatei, die von WWW-Servern beim Besuch einer Internetseite verschickt wird und auf der Festplatte des jeweiligen Nutzers zwischengespeichert wird. Wird der entsprechende Server erneut aufgerufen, sendet der Browser des Nutzers den zuvor empfangenen Cookie wieder zurück an den Server. Der Server kann dann die durch diese Prozedur erhaltenen Informationen auf verschiedene Arten auswerten. Durch Cookies kann z. B. das Navigieren auf einer Internetseite erleichtert werden.</span></p>
<p class="p1">a) Diese Webseite nutzt Cookies in folgendem Umfang:</p>
<p class="p1">- Transiente Cookies (temporärer Einsatz) <br />- Third-Party Cookies (von Drittanbietern)</p>
<p class="p1">b) Transiente Cookies werden automatisch gelöscht, wenn Sie den Browser schließen. Dazu zählen insbesondere die Session-Cookies. Diese speichern eine sogenannte Session-ID, mit welcher sich verschiedene Anfragen Ihres Browers der gemeinsamen Sitzung zuordnen lassen. Dadurch kann Ihr Rechner wiedererkannt werden, wenn Sie auf die Webseite zurückkehren. Die Session-Cookies werden gelöscht, wenn Sie sich ausloggen oder Sie den Browser schließen.</p>
<p class="p1">c) Sie können Ihre Browser-Einstellung entsprechend Ihren Wünschen konfigurieren und z. B. die Annahme von Third-Party-Cookies oder allen Cookies ablehnen. Wir weisen Sie jedoch darauf hin, dass Sie dann eventuell nicht alle Funktionen dieser Webseite nutzen können.</p>
<p class="p1"><strong><span class="s1">§ 3 Nutzung von Funktionen unserer Webseite </span></strong></p>
<p class="p1"><span class="s1">1. Neben der rein informatorischen Nutzung unserer Webseite bieten wir verschiedene Leistungen an, die Sie bei Interesse nutzen können. Dazu müssen Sie in der Regel weitere persönliche Daten angeben, die wir zur Erbringung der jeweiligen Leistung nutzen. Wenn zusätzlich freiwillige Angabe möglich sind, sind diese entsprechend gekennzeichnet. </span></p>
<p class="p1"><span class="s1">2. Sämtliche Funktionen auf dieser Webseite stellen wir unentgeltlich zur Verfügung. Bitte beachten Sie, dass daher kein Anspruch Ihrerseits auf diese Funktion und deren Umfang besteht. </span></p>
<p class="p1"><span class="s1">3. Bei Ihrer Kontaktaufnahme per E-Mail oder über das Kontaktformular werden Ihr Name, Ihre E-Mail-Adresse und Telefonnummer sowie Ihre Anschrift gespeichert, sofern dies notwendig ist, um Ihre Anfrage zu beantworten (z. B. Zusendung von Informationsmaterialien).</span></p>
<p class="p1"><strong><span class="s1">§ 4 Bestellung von Informationsmaterial </span></strong></p>
<p class="p1"><span class="s1">Wenn Sie eine Bestellung über das Online-Formular absenden möchten, bitten wir Sie um die Angabe bestimmter personenbezogener Daten. Wir verarbeiten und nutzen diese Daten dann, soweit dies zur Erbringung des jeweiligen Dienstes (Zusendung der Materialien) notwendig ist. Wir weisen ausdrücklich darauf hin, dass eine Bestellung in fremdem Namen, ohne Wissen des angegebenen Empfängers, nicht gestattet ist.</span></p>
<p class="p1"><strong><span class="s1">§ 5 SchuJu-Zertifikat </span></strong></p>
<p class="p1"><span class="s1">1. Auf unserer Webseite bieten wir Ihnen die Möglichkeit an, ein Onlinetraining zum Thema Jugendschutz zu absolvieren und einen Test zur Überprüfung der erlernten Kenntnisse zu machen („SchuJu"-Training). Neben einem Grundkurs (WBT = Web Based Training) I wird zusätzlich ein Aufbaukurs (WBT II) angeboten. </span></p>
<p class="p1"><span class="s1">Wenn Sie das „SchuJu"-Training online absolvieren möchten, müssen Sie sich hierfür registrieren. Die Registrierung ist notwendig, damit Sie nach erfolgreichem Abschluss ein personalisiertes Zertifikat erhalten können. Folgende personenbezogenen Daten werden daher von Ihnen benötigt: [Name, Vorname, E-Mail, Angaben zu Ihrer Tätigkeit und Unternehmen]. </span></p>
<p class="p1"><span class="s1">Für Unternehmen ist es möglich, auf Anfrage einen Gruppenzugang für ihre Mitarbeiter einrichten zu lassen. Bitte senden Sie uns dafür die Namen, Vornamen und Geburtsdaten der Teilnehmer sowie die vollständige Anschrift Ihres Unternehmens per E-Mail an: <a href="mailto:info@schu-ju.de">info@schu-ju.de</a>. Der Übersender sichert zu, dass die von ihm angegebenen Teilnehmer die Allgemeinen Datenschutz- und Nutzungsbestimmungen zur Kenntnis erhalten und in die Nutzung ihrer personenbezogenen Daten durch den Anbieter eingewilligt haben. </span></p>
<p class="p1"><span class="s1">2. Wir nutzen Ihre bei der Registrierung angegebene E-Mail-Adresse für die Zusendung eines persönlichen Passwortes. Das Passwort wird für die Anmeldung dann mit dem Benutzernamen benötigt. Wir verwenden für die Registrierung das sogenannte Doppel Opt-In-Verfahren, d. h. Ihre Registrierung ist erst abgeschlossen, wenn Sie zuvor Ihre Anmeldung über eine Ihnen zu diesem Zweck zugesandte Bestätigungs-E-Mail durch Klick auf den darin enthaltenen Link bestätigt haben. Andernfalls werden Ihre Daten gelöscht. Eine Weitergabe Ihrer E-Mail-Adresse an Dritte ist ausgeschlossen.</span></p>
<p class="p1"><span class="s1">3. Um die Ergebnisse der WBTs (I und II), die Anzahl der Teilnehmer und die personenbezogenen Daten der Teilnehmer für den Absender der Initiative „Arbeitskreis Alkohol und Verantwortung" des BSI (Bundesverband der Deutschen Spirituosen-Industrie und -Importeure e. V.), Urstadtstraße 2, 53129 Bonn sowie dessen Kooperationspartner, wie im Impressum des Internetauftritts <a href="../" target="_blank">http://www.schu-ju.de</a> und unter <a href="../9-0-Absender-und-Partner.html" target="_blank">„Absender und Partner"</a> genannt, zu evaluieren, wird mit Ihren Daten eine Datenbank erstellt. Die Datenbank wird zur Evaluierung, Nachbefragung und für die Einladung zum Aufbaukurs oder zur Wiederholung des WBT I genutzt. Mittels der Datenbank werden anonymisierte Statistiken erstellt (z. B. Anzahl an Zertifikaten in einem bestimmten Zeitraum). Diese Zahlen werden dem BSI und den „SchuJu"-Kooperationspartnern zur Verfügung gestellt. Einzelne Zahlen werden auch veröffentlicht (z. B. im CSR-Bericht des BSI).</span></p>
<p class="p1"><strong><span class="s1">§ 6 Weitergabe Ihrer Daten </span></strong></p>
<p class="p1"><span class="s1">Für die Durchführung der Auswertung des „SchuJu"-Trainings, (WBT I) und des „SchuJu"-Aufbaukurses (WBT II) sowie bei einer Bestellung über das Online-Formular werden Ihre Daten (erhoben bei der Registrierung zum WBT bzw. beim Versand der Bestellung) an die KESSLER Kommunikationsberatung, Wilhelminenstraße 29, 65193 Wiesbaden, weitergegeben. Diese Firma erstellt mit bestimmten Daten eine Datenbank zur Erfassung aller Teilnehmer und aller Ergebnisse der WBTs (I und II). Des Weiteren übernimmt die KESSLER Kommunikationsberatung die Pflege und Administration der Datenbank.</span></p>
<p class="p1"><strong><span class="s1">§ 7 Rechte auf Auskunft und Widerruf </span></strong></p>
<p class="p1"><span class="s1">1. Sie haben das Recht, von uns jederzeit Auskunft zu verlangen über die zu Ihnen bei uns gespeicherten Daten, sowie zu deren Herkunft, Empfängern oder Kategorien von Empfängern, an die diese Daten weitergegeben werden und den Zweck der Speicherung. </span></p>
<p class="p1"><span class="s1">2. Wenn Sie eine Einwilligung zur Nutzung von Daten erteilt haben, können Sie diese jederzeit widerrufen. Wenden Sie sich bitte per E-Mail an folgende Adresse: <a href="mailto:info@schu-ju.de">info@schu-ju.de</a>. In diesem Fall werden wir sämtliche gespeicherten Daten von Ihnen unverzüglich löschen. Bitte berücksichtigen Sie, dass es aus technischen oder organisatorischen Gründen zu einer Überschneidung zwischen Ihrem Widerruf und der Nutzung Ihrer Daten im Rahmen einer bereits laufenden Kampagne kommen kann. </span></p>
<p class="p1"><span class="s1">3. Alle Informationswünsche, Auskunftsanfragen oder Widersprüche zur Datenverarbeitung richten Sie bitte per E-Mail an <a href="mailto:info@schu-ju.de">info@schu-ju.de</a> oder an die unter § 1 Abs. 2 genannte Adresse.</span></p>
<p class="p1"><strong><span class="s1">§ 8 Datensicherheit</span></strong></p>
<p class="p1"><span class="s1">Wir fühlen uns der Sicherheit Ihrer Daten verpflichtet. Um einen unbefugten Zugang oder eine unbefugte Offenlegung zu verhindern, die Richtigkeit der Daten zu gewährleisten und die berechtigte Nutzung der Daten sicherzustellen, haben wir entsprechende technische und organisatorische Verfahren eingerichtet, um die Daten, die wir online erfragen, zu sichern und zu schützen. Dennoch können wir für die Offenlegung Ihrer Daten aufgrund von Fehlern bei der Datenübertragung und/oder unberechtigtem Zugriff durch Dritte keine Verantwortung oder Haftung übernehmen.</span></p>
<p class="p1"><strong><span class="s1">§ 9 Änderung der Nutzungsbedingungen </span></strong></p>
<p class="p1"><span class="s1">Wir behalten uns das Recht vor, einzelne Datenschutz- und Nutzungsbestimmungen jederzeit unter Beachtung der geltenden Datenschutzvorschriften zu ändern, sofern es aus technischen Gründen (z. B. Computervirus, Manipulation von oder Fehler in der Software/Hardware) oder rechtlichen Gründen notwendig ist. </span></p>
<p class="p1"><span class="s1">Stand: 2019<br /></span></p>

</div>
<br>
<br>
</div>
<jsp:include page="/include/footer.jsp"></jsp:include>

</body>
</html>